[package]
name = "Backend"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
postgres  = "0.19.13"
dotenv = "0.15.0"